### ISSUE TITLE
Error parsing server info when CPU info is unavailable

### ISSUE THREAD

**Issue by kevinkk525** [xperimental/nextcloud-exporter#11]
I'm running my nextcloud instance inside a lxd container and therefore the cpu lad info and the memory info is unvailable. 
So I get this error:

Error during scrape: Error parsing server info: strconv.ParseUint: parsing "N/A": invalid syntax

I still get an output from the exporter but only these 3 metrics are added:

nextcloud_auth_errors_total 0
nextcloud_scrape_errors_total 1
nextcloud_up 0

When using lxcfs then cpu load and memory info are available and everything works fine. 
I'm not sure if there are any other environments where cpuinfo might not be available so it might be a very minor issue.

**Comment by xperimental** [comment]
Thanks for reporting the issue, @kevinkk525 !

Could you add a copy of your serverinfo to this issue, so that I can put that in the test data?

**Comment by kevinkk525** [comment]
Ah I didn't think about that before doing the changes... Will try to replicate it in a virtual machine the next days and get back to you.
What information do you need? The contents of /proc?

**Comment by xperimental** [comment]
Thanks for trying to replicate this again! If you have it replicated you can also send me the instructions on how to do so, I'd be interested in that (have not used lxd for containerization before).

For the testing data I'd only need the contents of the serverinfo that nextcloud produces as this is the only data source the exporter uses: https://example.com/ocs/v2.php/apps/serverinfo/api/v1/info

You need to be authenticated for that request to work.

**Comment by kevinkk525** [comment]
This is a bit embarrassing but I can't replicate the issue in any VM.. 
I am using Ubuntu 19.04 server and install lxd using snap. But every attempt in a vm provides /proc/cpuinfo correctly even without lxcfs so it's weird that my actual host had problems with it.
And now even after removing lxcfs I get those memory and cpu information correctly..

I guess this is an non-reproducible problem..

**Comment by Wouter0100** [comment]
I've got the same issue.

```
2019/09/24 16:55:03 Nextcloud server: nextcloud.*****.** User: prometheus
2019/09/24 16:55:03 Listen on :9205...
2019/09/24 16:55:10 Error during scrape: Error parsing server info: strconv.ParseUint: parsing "N/A": invalid syntax
2019/09/24 16:55:14 Error during scrape: Error parsing server info: strconv.ParseUint: parsing "N/A": invalid syntax
2019/09/24 16:55:18 Error during scrape: Error parsing server info: strconv.ParseUint: parsing "N/A": invalid syntax
2019/09/24 16:55:24 Error during scrape: Error parsing server info: strconv.ParseUint: parsing "N/A": invalid syntax
2019/09/24 16:55:28 Error during scrape: Error parsing server info: strconv.ParseUint: parsing "N/A": invalid syntax
```

[info.xml.txt](https://github.com/xperimental/nextcloud-exporter/files/3647838/info.xml.txt)

**Comment by kevinkk525** [comment]
Can you post the output of https://example.com/ocs/v2.php/apps/serverinfo/api/v1/info
(adapt to your installation url of course)

**Comment by Wouter0100** [comment]
@kevinkk525 see my original post. It references a `info.xml.txt`, which is the output of the provided URL. :)

The .txt extension is to be able to upload it to Github. Github does otherwise not allow xml files.

**Comment by kevinkk525** [comment]
Nevermind, i was blind :D Thanks.

How did you install your server?

**Comment by Wouter0100** [comment]
Using the webinstaller by NextCloud. Then just proceeded in the web wizard. No hassle. :)

**Comment by kevinkk525** [comment]
Ah yes I meant your physical server/VM

**Comment by Wouter0100** [comment]
Its installed on a physical DirectAdmin server with Apache/NGINX.

**Comment by Wouter0100** [comment]
It was due open basepath, that the memory values weren't readable. I've temporary disabled open_basepath for this domain, which allowed the exporter to map the metrics.

**Comment by kevinkk525** [comment]
That's interesting, thanks. That'll make it reproducable and might be a common scenario.
In my case there was no cpuinfo in /proc which is quite uncommon.

**Comment by xperimental** [comment]
Thanks for providing the example data, @Wouter0100.

What would be your favorite way of handling this (apart from "not crashing") if the reported value is "N/A"?

- Completely omitting the metrics
- Setting the metric's value to a specific value (for example `0` or `-1`)

**Comment by Wouter0100** [comment]
Omitting would be preferred by us.

**Comment by kevinkk525** [comment]
+1 for omitting by me too.

**Comment by xperimental** [comment]
@Wouter0100 @kevinkk525 Please check if the change fixed the issue. We can reopen this bug if necessary.

**Comment by kevinkk525** [comment]
Thanks for fixing the issue. Since I can't reproduce the problem anymore, Wouter0100 will have to confirm it.
