### ISSUE TITLE
Specified minimum go version for building is too low

### ISSUE THREAD

**Issue by codeling** [xperimental/nextcloud-exporter#117]
Just tried building the latest version. The README mentions go needs to be >= 1.16; I did try with 1.18 (from Ubuntu 22.04), and it failed to build:
```
$ go version
go version go1.18.1 linux/amd64
$ make
CGO_ENABLED=0 go test -cover ./...
go: errors parsing go.mod:
PATH_TO/nextcloud-exporter/go.mod:5: unknown directive: toolchain
make: *** [Makefile:17: test] Fehler 1
 ```

On Ubuntu 24.04 (go version go1.22.2 linux/amd64) it worked

**Comment by xperimental** [comment]
That part in the readme has not been updated in a while :slightly_smiling_face: 

I have removed the mention of a specific version now, although per my understanding of Go Toolchain every version starting with 1.21 should work as long as it is allowed to download the toolchain.
