### ISSUE TITLE
storage totals?

### ISSUE THREAD

**Issue by codeling** [xperimental/nextcloud-exporter#119]
Does nextcloud expose the storage totals? There is the free space bytes, but there should also be the total number of bytes, no? I.e., either the quota, or if none is set, the total disk memory?

**Comment by xperimental** [comment]
Thanks for the question. The exporter only converts the statistics provided by the Nextcloud serverinfo application into a format parseable by Prometheus. As far as I know, these statistics do not contain the total space available in the system.

This might be a number that is not easy to get for Nextcloud anyway, depending on the environment where it is used. Usually you are much better off, getting these metrics from another exporter more suited to the task. For installations that use some kind of local filesystem, this might for example be the `node-exporter`.

**Comment by codeling** [comment]
ok, thanks for the clarification!
