### ISSUE TITLE
9205 not exposed

### ISSUE THREAD

**Issue by mattwhi** [xperimental/nextcloud-exporter#121]
Hi I'm attempting to run this docker which is running but the port isn't exposed and I can't access it

**Comment by TheRealKasumi** [comment]
Hi, I just randomly saw your question. Im not fully sure what your setup is and what you are trying to achieve. But I assume prometheus is running on your host and so want to forward container port `9205` to your host. You can do that by adding the `-p` parameter to your docker command. See the [docker networking documentation](https://docs.docker.com/engine/network/).

`-p <host_port>:<container_port>`

So if you take the docker run command from the ReadMe:

`docker run --rm -it ghcr.io/xperimental/nextcloud-exporter --login --server https://nextcloud.example.com`

You could try this instead:

`docker run --rm -p 9205:9205 -it ghcr.io/xperimental/nextcloud-exporter --login --server https://nextcloud.example.com`

Maybe that helps. Good luck.

**Comment by xperimental** [comment]
@mattwhi The image provided for the exporter contains the necessary metadata for automatically exposing the exporter's port. I'm assuming there's a misunderstanding in what this actually means. @TheRealKasumi's comment contains some valuable pointers that might help you.

I'm closing this now, feel free to reopen with more information in case something actually is broken.
