### ISSUE TITLE
HTTPS with self-signed Certificate possible?

### ISSUE THREAD

**Issue by b-m-f** [xperimental/nextcloud-exporter#28]
Right now I am encountering the following error:
```
level=error msg="Error during scrape: Get \"https://nextcloud.local/ocs/v2.php/apps/serverinfo/api/v1/info\": x509: certificate is valid for localhost, not nextcloud.local"
```

Any way to accept self-signed certificates?

**Comment by xperimental** [comment]
Hi,

Currently there is no option for turning off TLS certificate validation, but it's certainly possible to add this. I'm not sure if this would fix the issue mentioned in your error, though, as this is not related to the signature chain validation but the hostname validation.

Another idea: Is the monitoring running on the same host as the Nextcloud instance? In that case it would also be an alternative to just skip TLS and go with plain HTTP.

**Comment by b-m-f** [comment]
Hi @xperimental ,

unfortunately plain HTTP won't work in my setup.

If you can point me to the right area of the code, I can help with implementing 'skip-tls'

**Comment by xperimental** [comment]
Sorry, for the day, I have been a bit busy the last days. I'll probably get to a bit of open-source again in the next days, but I can't promise anything.

If you want to take a stab at the issue yourself, the TLS options can be set on the `Transport` used by the `http.Client` [used in the collector](https://github.com/xperimental/nextcloud-exporter/blob/master/collector.go#L79). See also: https://golang.org/pkg/net/http/#Transport

**Comment by b-m-f** [comment]
@xperimental Just finished a project of mine as well. Looks like @jacksgt took care of this already :)

**Comment by xperimental** [comment]
Just merged @jacksgt 's PR. Please check if this solves your issue. Feel free to reopen otherwise.

**Comment by Nicalicious** [comment]
Bringing this one back up. --tls-skip-verify does not work with docker run --rm -it xperimental/nextcloud-exporter --login --server https://nextcloud.domain.com.

 It yields FATA Error during login: error getting version: error connecting: error connecting: Get "https://nextcloud.domain.com/status.php": x509: certificate signed by unknown authority.

**Comment by xperimental** [comment]
@Nicalicious Thanks for the comment. It seems we forgot to add the flag to the client used in the login flow as well.
