### ISSUE TITLE
[Feature Request] Metric for outstanding updates

### ISSUE THREAD

**Issue by serverfriendsorg** [xperimental/nextcloud-exporter#30]
Hey, thanks for writting this exporter. I was wondering if there is a possibility to have a metric for nextcloud updates as I want to alert with prometheus if there are any updates.

**Comment by xperimental** [comment]
Apparently statistics about the apps have been added to the serverinfo response. :tada:
I've added these metrics in the linked PR. Please check if that works for you...

**Comment by serverfriendsorg** [comment]
Thanks for the quick PR. I've tested it and it works perfect.
```
# HELP nextcloud_apps_updates_available_total Number of apps that have available updates
# TYPE nextcloud_apps_updates_available_total gauge
nextcloud_apps_updates_available_total 0
```
