### ISSUE TITLE
Add version flag 

### ISSUE THREAD

**Issue by KornKalle** [xperimental/nextcloud-exporter#34]
Hello,

Thanks for providing this nextcloud-exporter, I am enjoying it so far :)

Currently, I am writing an ansible role for provisioning it easily, and I also wanted to implement a mechanic to update it automatically.
To achieve this, it would be awesome if the exporter itself could return it's version.

Do you have any plans to add this?

**Comment by xperimental** [comment]
Good to hear that it works for you. :tada:

The last release already embedded release information in the exporter binary, which is used to create a metric. It should be quite easy to add a `--version` flag or something equivalent.

If you are thinking about hooking this up to another application/script then having a machine-readable output would probably be desirable?

**Comment by KornKalle** [comment]
Yes, it would be great if only the version gets return insted of the current info log.

I also tried adding it locally, but as I never worked with go before i got quite confused with how to achieve this with the pflag dependency and the flag error handling

**Comment by xperimental** [comment]
Can you have a look at the [version-info](https://github.com/xperimental/nextcloud-exporter/tree/version-info) branch and comment if this would be okay? It's the simplest implementation of such a flag. I was thinking of having the possibility of outputting the information as a simple JSON struct (version and git commit-hash) for easier consumption in other tools, but I don't know if this is necessary.

Please tell me, if you need help building the version in the branch.

**Comment by KornKalle** [comment]
I just built it locally and it is working like a charm, this would be enough for making it comparable to the latest release and updating it if needed.

In case you are interested, I put the ansible role for installing the exporter as systemd service on github, too:
https://github.com/KornKalle/ansible-nextcloud-exporter

It's working very well in combination with our kinda large Nextcloud instance (~2k Users).

Thanks a lot!
