### ISSUE TITLE
Consider JSON API

### ISSUE THREAD

**Issue by J0WI** [xperimental/nextcloud-exporter#39]
The Nextcloud API supports JSON. This may have several advantages compared to the XML format and parser in terms of performance, security and portability.

https://docs.nextcloud.com/server/stable/developer_manual/core/externalapi.html#output

**Comment by xperimental** [comment]
Thanks for the reminder. I had stumbled over the alternative output format last time I looked at the docs, don't know why I missed it the first time or if it was added after I created the first implementation of the exporter.

Don't know if this will change much in regards to security and portability but it should shave off a few bytes from the transferred response.
