### ISSUE TITLE
NC22: Replace admin user with API token

### ISSUE THREAD

**Issue by J0WI** [xperimental/nextcloud-exporter#42]
This is just a heads up that the upcoming release does not require admin privileges for monitoring anymore: https://github.com/nextcloud/serverinfo/pull/269

**Comment by xperimental** [comment]
Thanks for the heads-up! I'll keep this open until it's implemented...

**Comment by mrueg** [comment]
I think nextcloud 22 supports this now, would be nice to be able to drop admin permissions

**Comment by xperimental** [comment]
I assume one of my instances will upgrade to Nextcloud 22 soon. I'll do an implementation then.

**Comment by Kybeer** [comment]
Hi @xperimental 
Do you have any progress to share on the token login implementation?

**Comment by xperimental** [comment]
@Kybeer there has been no progress on this feature yet. But I noticed last week that one of my instances is now running NC22.

**Comment by J0WI** [comment]
Instead of a user/password the new request needs just a `NC-Token` header, that's easy to implement. But this also requires a new config option and maybe some logic to let the user choose between the two authentication mechanism.

https://github.com/nextcloud/serverinfo/pull/269/files#diff-b86b31801e087ecdaaf18d4d9db5f4362120f71c7173386d118e94b2f1899ac9

**Comment by xperimental** [comment]
@J0WI Thanks! I already had a look about a week ago which led to [the `nc22-token` branch](https://github.com/xperimental/nextcloud-exporter/tree/nc22-token). There are still some errors in it, that's why there's no pull-request for it yet. But I'll get there "soon" 🙂

**Comment by xperimental** [comment]
There's a pull-request for this feature now. Also, feel free to try out the image built from that feature-branch:

```
xperimental/nextcloud-exporter:0.4.0-15-gbb88fb6
ghcr.io/xperimental/nextcloud-exporter:0.4.0-15-gbb88fb6
```

**Comment by mrueg** [comment]
FWIW I've created a PR to allow setting up the token in https://github.com/nextcloud/docker/pull/1656

**Comment by xperimental** [comment]
If there is no negative feedback about this change in the next days, I'll merge it and prepare a new release afterwards.

**Comment by mrueg** [comment]
@xperimental any plans to create that release soon? :)

**Comment by xperimental** [comment]
Sorry, the past days were busier than I expected. I'll probably do the release in the next days. The good news is that another bug was found in the meantime. :slightly_smiling_face:
