### ISSUE TITLE
FATA Error during login: error getting version: non-ok status: 404

### ISSUE THREAD

**Issue by olegsidokhmetov** [xperimental/nextcloud-exporter#43]
Hello!

When I use command `nextcloud-exporter --login --server http://my_ip/`

I get error 
```
INFO nextcloud-exporter 0.4.0
INFO Starting interactive login on: http://my_ip/
**FATA Error during login: error getting version: non-ok status: 404**
```

Do not understand  what is wrong :(

and also:

nextcloud-exporter --login --server https://name_of_server
INFO nextcloud-exporter 0.4.0
INFO Starting interactive login on: https://name_of_server
FATA Error during login: error getting version: error connecting: error connecting: Get "https://name_of_server/status.php": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by xperimental** [comment]
In the first case (404, not found) I'd say the configuration of your webserver does not map the IP to the vhost Nextcloud is running on and in the second case (timeout) it sounds like a network issue. What happens when you use, for example, `curl` to fetch the `status.php`?

**Comment by olegsidokhmetov** [comment]
> 
> 
> In the first case (404, not found) I'd say the configuration of your webserver does not map the IP to the vhost Nextcloud is running on and in the second case (timeout) it sounds like a network issue. What happens when you use, for example, `curl` to fetch the `status.php`?

Thank you very much for your message. I already solved the problem
