### ISSUE TITLE
Counts number of authentication errors encountered by the collector

### ISSUE THREAD

**Issue by DanSman** [xperimental/nextcloud-exporter#48]
Hey

Nice exporter! 

I just have one question:
Is the number of authentication failures collected when trying to log in to the site itself or what is that? If so, I just tried that but nothing comes up in the Grafana dashboard. I can't find it in the api itself either. So I think the exporter is meant if it can't connect?

Thanks!

**Comment by xperimental** [comment]
Yes, these are the authentication issues that happened to the exporter itself while getting the data from Nextcloud. If this is counting up it usually means that the other metrics are not available.

I am getting that the description does not make this clear enough. Do you have a suggestion for a better description?

**Comment by DanSman** [comment]
Maybe:
Counts the number of authentication failures from the collector itself. Not Website!

**Comment by xperimental** [comment]
I have changed how the authentication errors are reported. I hope this will clear up the confusion around this metric.
