### ISSUE TITLE
JSON ServerInfo parser expects uint64 for db size, NC gives a string

### ISSUE THREAD

**Issue by Lymkwi** [xperimental/nextcloud-exporter#50]
After updating to NC22 I decided to update my nextcloud exporter and noticed that most of my metrics were gone. It turns out `nextcloud-exporter` fails to parse part of the metrics it receives. I get
```
ERRO Error during scrape: can not parse server info: json: cannot unmarshal string into Go struct field Database.ocs.data.server.database.size of type uint64
```
This does make sense since the `serverinfo` parser tries to fill in a `Database`, which `size` field is, according to [this line](https://github.com/xperimental/nextcloud-exporter/blob/master/serverinfo/serverinfo.go#L171), a `uint64`. At the same time, fetching the JSON version of my instance's metrics gave me this for the `ocs.data.server.database` : 
```json
"database":{"type":"mysql","version":"10.5.12","size":"80633856"}
```

I do not know which one is right, whether this is a problem with `nextcloud-exporter` expecting an int where there is a string, or nextcloud yielding a string for an int (which might be a new behaviour too, I don't know). I managed to reproduce this on the docker image as well of course.

Changing the expected type works but tests fail, so this does not seem to be the intended behaviour.

EDIT: I dug a little deeper, and this might just be a side effect of the fact that strings in XML can be implicitly converted as ints while parsing, while they can't in JSON. According to [line 96 of lib/DatabaseStatistics.php](https://github.com/nextcloud/serverinfo/blob/ee0df3eb9bbca32874ffd440023b6318d5c08c09/lib/DatabaseStatistics.php#L96) in the `serverinfo` app, this metric is intended to be returned as a string.

**Comment by xperimental** [comment]
It looks like the schema changed in [Nextcloud 22](https://github.com/nextcloud/serverinfo/commit/ee0df3eb9bbca32874ffd440023b6318d5c08c09), so this should be an issue for everyone using the exporter with NC22 and not just with the recent version of the exporter.

**Comment by xperimental** [comment]
@Lymkwi Can you check if the fix works for you? You can either build the exporter from the `fix-nc22` branch yourself or try the docker image `xperimental/nextcloud-exporter:0.4.0-12-gde29a28` (only built for amd64, for now).

**Comment by Lymkwi** [comment]
I can confirm that #51 does fix it for me. All metrics are back, and no errors reported. As expected, this is new to NC-22 and some weird side effect of recently switching to JSON.
Thank goodness this was caught quickly!

**Comment by fkocik** [comment]
Hi

Got same problem here.
I have 4 Nextcloud instances (2 x v21.0.3.1 / 1 x 22.1.1.2 / 1 x 22.2.0.2).
I lost metrics for the 22.x instances after NC upgrade with *latest* exporter image.
I just tested with `0.4.0-12-gde29a28` image : it fixes the problem, metrics are now successfully scrapped for all instances with the same image.

So, I can confirm that the #51 PR fixes the bug and is still compliant with older (21.x) version of NC.

Regards

**Comment by xperimental** [comment]
Great. Thanks for reporting the issue and testing the fix! :rocket:
