### ISSUE TITLE
Token auth not working

### ISSUE THREAD

**Issue by tsrats** [xperimental/nextcloud-exporter#57]
Hello! I am trying to use only token auth, but am having issues. I made the token on my Nextcloud server, but I can not get the exporter to use it. I tried with Env values first, and the logs said I need a username. Putting a username in, and then the logs say I need a password. It seems to ignore the token. I tried with putting the values in a config file for the container, but the same errors occur. The container will only start with a username and password.

**Comment by tsrats** [comment]
config output and ps showing it is using the config:

/ $ cat config.yaml 
# required
server: "https://nextcloud.domain.tld"
# required for token authentication
authToken: "alongstringtokenhere"
# required for username/password authentication
username: "admin"
password: "adminpasswordhere"
# optional
listenAddress: ":9205"
timeout: "5s"
tlsSkipVerify: true
/ $ ps aux
PID   USER     TIME  COMMAND
    1 nobody    0:00 /bin/nextcloud-exporter --config-file=/config.yaml
   13 nobody    0:00 sh
   21 nobody    0:00 ps aux
/ $

**Comment by jhjacobs81** [comment]
unfortunatly, i have the same issue :(

have you gotten any further with it?

**Comment by tsrats** [comment]
No, still having the issue. I thought it may be related somehow to running nextcloud's docker image, but Ive switched to the full install on a VM and same issue.

**Comment by jhjacobs81** [comment]
yep, i'm running multiple instances, version 22 and 23, docker and not docker :) they all have this issue

**Comment by xperimental** [comment]
Which version of the nextcloud-exporter are you using? I noticed that the last "master" build did not properly update the `latest` tag of the Docker images. I pushed the tag manually for now, this will be properly fixed later.

So if you were using the "latest" tag of the Docker image before, please try again now.

**Comment by tsrats** [comment]
Thanks for the update! It is working now. 

(I am running on ARM, so I had to use the tag 0.4.0-13-g3abc1f8, not latest, since that only seems to have x64 right now on docker hub, but this tag does work)

**Comment by xperimental** [comment]
I might have forgotten to update the tag for the arm64 variant yesterday. Sorry for that. I plan to fix the build soon.

**Comment by xperimental** [comment]
Does it work for you as well, @jhjacobs81 ? You mentioned that you had the issue with the non-dockerized version as well. There I do not know what should be causing the issue yet.

**Comment by xperimental** [comment]
I'm closing this now, because I don't know what the issue for @jhjacobs81 was. Feel free to comment here if you still have an issue with the exporter.

**Comment by jhjacobs81** [comment]
my apologies, there where xmas holidays and all :) i will check tonight!

**Comment by mator** [comment]
is there any docs on how to create auth token for admin user on nextcloud server ? thanks!
