### ISSUE TITLE
Somehow I get lots of strange HTTP requests from the nextcloud-exporter container

### ISSUE THREAD

**Issue by clst** [xperimental/nextcloud-exporter#61]
nextcloud log output:
```
10.0.2.100 - - [26/Dec/2021:20:56:54 +0000] "\x16\x03\x01\x02" 400 483 "-" "-"
10.0.2.100 - - [26/Dec/2021:20:56:54 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 200 2394 "-" "nextcloud-exporter/0.4.0-15-g30435c5"
10.0.2.100 - - [26/Dec/2021:20:57:09 +0000] "\x16\x03\x01\x02" 400 483 "-" "-"
10.0.2.100 - - [26/Dec/2021:20:57:09 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 200 2389 "-" "nextcloud-exporter/0.4.0-15-g30435c5"
10.0.2.100 - - [26/Dec/2021:20:57:14 +0000] "\x16\x03\x01\x02" 400 483 "-" "-"

```

I use docker.io/library/nextcloud:latest and docker.io/xperimental/nextcloud-exporter:latest with an auth token on the internal podman lan on aarch64.

**Comment by xperimental** [comment]
This looks weird indeed... I'll have a look at my own logs if I can reproduce this.

What method do you use to pass the auth-token to the exporter?

**Comment by mrueg** [comment]
According to https://stackoverflow.com/a/60144651 this might be a client (likely nextcloud-exporter then) trying to connect via https instead of http to an http endpoint.

**Comment by clst** [comment]
Ah that could be. Nextcloud is behind a reverse proxy with SSL termination and configured for transparent https.

nextcloud-exporter runs on podman behind the proxy, so it should just do plain http on the host port.

this is my command line:

```
podman run -p8017:9205 --rm -it xperimental/nextcloud-exporter --auth-token=0d16f[snip]6ac0e --server http://podmanhost:8011
```

It works fine, just with those extra connections.

**Comment by xperimental** [comment]
I'm sorry, but I don't quite get how your configuration is set up. What application is listening on hostport `podmanhost:8011`? Is `10.0.2.100` the IP you would expect the nextcloud-exporter to have? Is there anything else running on that host, maybe something filtering the traffic?

I have tried reproducing it by pointing an exporter to a HTTP-URL of a Nextcloud instance, but I only see one HTTP request on it, not a second invalid one. I have both looked at the log of the server (Apache2 in my case) and at a Wireshark capture on the interface.

**Comment by clst** [comment]
Yes, 8011 on the host is port 80 in the nextcloud pod. Maybe something in podman's rootless networking is interfering. But it would be the first time that happened. I'll try running nextcloud with root and its own network interface and connect directly to that one.

Only container running with root is the reverse proxy but that isn't even used in this scenario.

**Comment by clst** [comment]
Funny thing I just tried using https for the exporter but then it fails:
`ERRO Error during scrape: Get "https://podmanhost:8011/ocs/v2.php/apps/serverinfo/api/v1/info?format=json": http: server gave HTTP response to HTTPS client`

and the nextcloud log looks a bit different:
```
10.0.2.100 - - [27/Dec/2021:23:14:39 +0000] "\x16\x03\x01" 400 483 "-" "-"
```
last byte is missing. And the scrape fails.

**Comment by xperimental** [comment]
> I am very sorry for causing you all that extra work.

No worries. Happy to help.

Great that you found the issue and many thanks for coming back to us with the cause. Should I close the issue or do you want to do that?

**Comment by clst** [comment]
Oops I just forgot. Thanks again!
