### ISSUE TITLE
where are the remaining values?

### ISSUE THREAD

**Issue by badsmoke** [xperimental/nextcloud-exporter#7]
Hello, thank you for the program. But where are the remaining values? How database size? Version number? ... These are all available in the API but I don't find them in the Metrics

**Comment by xperimental** [comment]
Hello @badsmoke .

Thanks for the input and sorry for the delay. I had first only added the metrics I was interested in, so some were left out. I just added some more, for example the ones you mentioned like versions and database size. Is there another one that you are missing?

**Comment by xperimental** [comment]
@badsmoke I'm closing this now. If you need anything else, please feel free to reopen this issue.
