### ISSUE TITLE
[Feature Request] add num_shares_mail and num_shares_room metrics

### ISSUE THREAD

**Issue by orandev** [xperimental/nextcloud-exporter#75]
Hello,
Thanks for your exporter.

Could you add the following 2 metrics to nextcloud_shares_total please?

num_shares_mail
num_shares_room

https://github.com/nextcloud/serverinfo/blob/master/lib/ShareStatistics.php#L54
https://github.com/nextcloud/serverinfo/blob/master/lib/ShareStatistics.php#L55

**Comment by xperimental** [comment]
Hi @orandev. Sorry for the delayed response, but I have not worked on my hobby projects in a few weeks now.

This seems like a good idea, I don't think these share types existed when I originally wrote the code. Can't promise when the change will happen, but I have it on my mind.
