### ISSUE TITLE
Error:"Error during scrape" while executing the Nextcloud-Exporter 

### ISSUE THREAD

**Issue by dikshab0202** [xperimental/nextcloud-exporter#86]
Hi Team,
Observing an error while executing the nextcloud-exporter.
**Error:** "Error during scrape"

Observed that the nextcloud metrics are not reflecting on my IP "http:35.90.155.4:9205/metrics"
**ISSUE :** The exporter is not able to read the json on the below url. Instead of a JSON, the URL is showing a xml formatted data.
**URL :** http://35.90.155.4:9205/ocs/v2.php/apps/serverinfo/api/v1/info?format=json

It would be helpful if you can go through the below steps and screenshots and guide me with your solutions. 

**COMMANDS :** 
1. Token authentication (Token generated with the following steps: login to Nextcloud -> Personal setting -> Security -> Devices & Sessions -> Add and create new app password)
Note: documentation didn't work for generating token.
        Set token (using the occ console application), go inside path: “/var/www/nextcloud” to use occ command.
        ```
        occ config:app:set serverinfo token --value "$TOKEN"
        ```
       Above command is not running directly, I ran like this : 
        ```
        sudo -u www-data php occ occ config:app:set serverinfo token --value "$TOKEN"
        ```

2. Start Nextcloud using Username and Password authentication.
        ```
        ./nextcloud-exporter --login <USERNAME> <PASSWORD> --server http:35.90.155.4
        ```

3. To access metrics for nextcloud, run the following command with username and password generated by step2:
        ```
        ./nextcloud-exporter -u <YOUR_USERNAME> -p <YOUR_PASSWORD> --server http:35.90.155.4:9205
        ```
        
 ![image (2)](https://github.com/xperimental/nextcloud-exporter/assets/101187392/4801ffcb-0ed3-4b38-ba31-cbb70e62b2de)   
![Screenshot 2023-05-17 at 15 54 54](https://github.com/xperimental/nextcloud-exporter/assets/101187392/a472612d-9d53-4a0f-abcf-0fe609d2c59a)

**Comment by xperimental** [comment]
It looks to me like you are not using the correct server-URL to point the exporter to your Nextcloud instance. Port `9205` is the default port of the exporter, so you're pointing the exporter at itself, which is not a valid configuration. Use the port of your Nextcloud instance in that URL instead.

**Comment by dikshab0202** [comment]
> It looks to me like you are not using the correct server-URL to point the exporter to your Nextcloud instance. Port `9205` is the default port of the exporter, so you're pointing the exporter at itself, which is not a valid configuration. Use the port of your Nextcloud instance in that URL instead.

@xperimental  Thank you for the solution; it resolved my issue!

**Comment by xperimental** [comment]
@dikshab0202 You're welcome.
