### ISSUE TITLE
[Question] Set token in config file?

### ISSUE THREAD

**Issue by hobyte** [xperimental/nextcloud-exporter#87]
Right now, the access token for the token authentication has to be set with the `occ` command.
Is it possible to set this token in a config file? This would make deployment easier, especially in cloud environments.

**Comment by xperimental** [comment]
Hi @hobyte ,

How the token is configured in Nextcloud's systeminfo app is out of the scope of this exporter. I'm not sure where the `occ` command writes the configuration to, but my assumption is that this depends on the configuration of Nextcloud and, possibly, is saved to the main database used by Nextcloud.

My suggestion is for you to reach out to one of the nextcloud projects (maybe [nextcloud/serverinfo](https://github.com/nextcloud/serverinfo/), but maybe a different one as "app configuration" is a more generic topic) and talk with them about this topic. Once the alternatives to the current command-line approach are clear, they can definitely be added to the documentation here.
