### ISSUE TITLE
expose CPU and memory statistics

### ISSUE THREAD

**Issue by raboof** [xperimental/nextcloud-exporter#95]
seem to be already present in the serverinfo

**Comment by xperimental** [comment]
Hi @raboof. Thanks for you idea and implementation.

Exposing the CPU metrics that are included in the serverinfo offered by Nextcloud was already suggested in #27. I said back then that there are more specialized exporters for getting those metrics. In my opinion this should not be the nextcloud-exporter's job to provide the node/host metrics.

My suggestion would be the same as in that PR: use `node_exporter` to get the host metrics. It can do CPU and memory, but a lot more (which can also be disabled if not needed) and can also run inside a container.

**Comment by raboof** [comment]
Gotcha, that makes sense. It's kinda nice how nextcloud-exporter can be ran on the monitoring machine and fetch these metrics over the nicely token-authenticated connection. I'm not sure if we'll manage to run node_exporter on the production machine, as the main reason we want to monitor it is that it's rather tight on memory already :). So I do see value in exposing these values through nextcloud-exporter, even if node_exporter might be a better choice in many situations. Happy to make any changes to the PR if that helps ;).

**Comment by xperimental** [comment]
`node_exporter` shouldn't consume that many resources, especially if you only configure it to expose the ones you need.
