### ISSUE TITLE
Is there a way to remote write

### ISSUE THREAD

**Issue by Badb0yBadb0y** [xperimental/nextcloud-exporter#97]
Hi,

Prometheus has this feature: 

https://docs.sysdig.com/en/docs/installation/sysdig-monitor/install-prometheus-remote-write/#configure-remote-write-in-prometheus-server

Somehow can I load remote_write specific settings into the container?
I see the scrape settings can be changed, but how to pass those parameters to the container?

I'd like to load somehow a config like this with remote write:
https://github.com/xperimental/nextcloud-exporter#scrape-configuration

I'm running the container like this at the moment:

`docker run -d -p 9205:9205 --name nextcloud_exporter --rm -it xperimental/nextcloud-exporter --auth-token 12345 --server https://myserverurl`

**Comment by xperimental** [comment]
Hi. I don't quite understand how your question relates to the exporter.

`remote_write` and the scrape configuration are both configuration options of Prometheus and not the exporter itself. You can configure Prometheus to scrape the data from the exporter and then use remote-write to send it to another Prometheus instance or other compatible endpoint, but all of this is not really of concern to the exporter.

**Comment by xperimental** [comment]
Closing because there was no reply. Please reopen if you need more assistance.
