### ISSUE TITLE
Is there a build for 32-bit ARM?

### ISSUE THREAD

**Issue by aabrilfl13** [xperimental/nextcloud-exporter#98]
I notice that is not for linux/arm/v7, is there any way to install it no raspberry pi?

**Comment by m0rtalis** [comment]
From the README, second line of text
> The preferred way to use `nextcloud-exporter` is by running the provided Docker image.

...which is platform agnostic

Otherwise you can [build it from source for raspi](https://github.com/xperimental/nextcloud-exporter/blob/master/README.md#build-from-source)

**Comment by xperimental** [comment]
@aabrilfl13 I currently only build the `arm64` version, but it should be possible to build the 32-bit ARM version as well. Are you using an older version of Raspberry Pi or why do you prefer to not use the 64-bit version?

**Comment by aabrilfl13** [comment]
> @aabrilfl13 I currently only build the `arm64` version, but it should be possible to build the 32-bit ARM version as well. Are you using an older version of Raspberry Pi or why do you prefer to not use the 64-bit version?

I installed 32 bit due I have 2GB of RAM, still better to have 64bit version?

**Comment by xperimental** [comment]
@aabrilfl13 Yes, I'd go with the 64-bit version even if you have less than 4GB of RAM.

But, like @m0rtalis mentioned the source is easily buildable for other architectures. Go is also capable of easy cross-compilation. To compile an armv7 binary, even when not on armv7 you can use this command once you have cloned the repository and a recent Go compiler present (I'd recommend the most recent one 1.21.0 :slightly_smiling_face: ):

```
GOARCH=arm GOARM=7 make build-binary
```
